name: "Monthly Vote Job"
on:
  schedule:
    - cron: '5 0 1 * *'  # 매달 1일 00:05 UTC
jobs:
  supabase-cron:
    runs-on: ubuntu-latest
    steps:
      - name: "Call Supabase Edge Function"
        run: |
          # 함수 URL
          FUNCTION_URL="https://xtijtefcycoeqludlngc.functions.supabase.co/monthly-job"
          SLACK_WEBHOOK="https://hooks.slack.com/services/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"
          # 호출 (POST)
          #  -s : silent, -w : write-out
          # 실제로는 Authentication 필요 없다면 이대로, 필요하면 베어러 토큰 등 추가
          RESPONSE_CODE=$(curl -X POST \
            -o /dev/null \
            -s \
            -w "%{http_code}" \
            "${FUNCTION_URL}"
          )
          
          echo "RESPONSE_CODE = $RESPONSE_CODE"

          # 성공/실패 체크
          if [ "$RESPONSE_CODE" -eq "200" ]; then
            echo "Monthly vote job succeeded!"
            # (선택) Slack 알림
            curl -X POST -H 'Content-type: application/json' \
                 --data '{"text":"Monthly vote job success!"}' $SLACK_WEBHOOK
          else
            echo "Monthly vote job failed with code $RESPONSE_CODE"
            # Slack 알림
            curl -X POST -H 'Content-type: application/json' \
                 --data "{\"text\":\"Monthly vote job failed. Code: $RESPONSE_CODE\"}" $SLACK_WEBHOOK
            exit 1
          fi