// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9pi60hMi0yxA9KnA-zM3aTsYE1wINbOE',
    appId: '1:853406219989:web:9e6f90b09b314be2bcac5c',
    messagingSenderId: '853406219989',
    projectId: 'picnic-423500',
    authDomain: 'picnic-423500.firebaseapp.com',
    storageBucket: 'picnic-423500.firebasestorage.app',
    measurementId: 'G-KREGF7NTP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm0_bdB3-ky3Za-7H4Ysgj1zci6Yb-NzU',
    appId: '1:853406219989:android:93153a1e2d8a391cbcac5c',
    messagingSenderId: '853406219989',
    projectId: 'picnic-423500',
    storageBucket: 'picnic-423500.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4ycAYa1PQYtUZEmIvF3NkOh8YMKahh1o',
    appId: '1:853406219989:ios:5a5d708a16024a79bcac5c',
    messagingSenderId: '853406219989',
    projectId: 'picnic-423500',
    storageBucket: 'picnic-423500.firebasestorage.app',
    androidClientId: '853406219989-8ji54q3mci0tqvin09aigsghk5vo4t0i.apps.googleusercontent.com',
    iosClientId: '853406219989-un8ik8up6hoi6dsgknc0uabn5n60pbp8.apps.googleusercontent.com',
    iosBundleId: 'io.iconcasting.picnic.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4ycAYa1PQYtUZEmIvF3NkOh8YMKahh1o',
    appId: '1:853406219989:ios:52e09030672f28c0bcac5c',
    messagingSenderId: '853406219989',
    projectId: 'picnic-423500',
    storageBucket: 'picnic-423500.firebasestorage.app',
    androidClientId: '853406219989-8ji54q3mci0tqvin09aigsghk5vo4t0i.apps.googleusercontent.com',
    iosClientId: '853406219989-56cu5ck4pc60flpsur76hil5v8bj23fs.apps.googleusercontent.com',
    iosBundleId: 'io.iconcasting.picnic.mac',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9pi60hMi0yxA9KnA-zM3aTsYE1wINbOE',
    appId: '1:853406219989:web:ed71b02c41d8af50bcac5c',
    messagingSenderId: '853406219989',
    projectId: 'picnic-423500',
    authDomain: 'picnic-423500.firebaseapp.com',
    storageBucket: 'picnic-423500.firebasestorage.app',
    measurementId: 'G-GWP6Z8F6GM',
  );

}