name: picnic_app
description: "Picnic App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.5+110507

environment:
    sdk: '>=3.3.1 <4.0.0'

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    shimmer: ^3.0.0
    sentry_flutter: ^8.9.0
    flutter_native_splash: ^2.4.1
    universal_platform: ^1.1.0
    url_launcher: ^6.3.0
    flutter_cache_manager: ^3.4.1
    another_flutter_splash_screen: ^1.2.1
    flutter_launcher_icons: ^0.14.1
    google_mobile_ads: ^5.1.0
    appinio_social_share: ^0.3.2
    logger: ^2.4.0
    flutter_secure_storage: ^9.2.2
    flutter_card_swiper: ^7.0.1
    file_picker: ^8.0.6
    animated_digit: ^3.2.3
    open_filex: ^4.5.0
    supabase_extensions: ^1.0.1
    shared_preferences: ^2.3.2
    image_picker: ^1.1.2
    riverpod: ^2.5.1
    package_info_plus: ^8.0.2
    flutter_riverpod: ^2.5.1
    flutter_svg: ^2.0.10+1
    load_switch: ^2.1.0
    riverpod_annotation: ^2.3.5
    flutter_quill: ^10.7.5
    timeago: ^3.7.0
    intl: ^0.19.0
    camera: ^0.11.0+2
    flutter_screenutil: ^5.9.3
    overlay_loading_progress: ^1.0.1
    reflectable: ^4.0.6
    json_annotation: ^4.9.0
    cached_network_image: ^3.4.1
    card_swiper: ^3.0.1
    infinite_scroll_pagination: ^4.0.0
    flutter_keyboard_visibility: ^6.0.0
    font_awesome_flutter: ^10.7.0
    overlay_support: ^2.1.0
    screen_protector: ^1.4.2+1
    bubble: ^1.2.1
    supabase_flutter: ^2.6.0
    google_sign_in: ^6.2.1
    sign_in_with_apple: ^6.1.2
    kakao_flutter_sdk: ^1.9.6
    kakao_flutter_sdk_user: ^1.9.6
    firebase_core: ^3.5.0
    image: ^4.2.0
    image_gallery_saver_plus: ^3.0.5
    in_app_purchase: ^3.2.0
    photo_manager: ^3.4.0
    permission_handler: ^11.3.1
    flutter_markdown: ^0.7.3+1
    vector_math: ^2.1.4
    path_provider: ^2.1.4
    app_tracking_transparency: ^2.0.6
    freezed_annotation: ^2.4.4
    app_links: ^6.3.2
    http: ^1.2.2
    deepl_dart: ^1.4.0
    watcher: ^1.1.0
    jwt_decoder: ^2.0.1
    pool: ^1.5.1
    firebase_analytics: ^11.3.2
    timezone: ^0.9.4
    connectivity_plus: ^6.1.0
    visibility_detector: ^0.4.0+2
    image_cropper: ^8.0.2
    youtube_player_iframe: ^5.2.0
    flutter_inappwebview: ^6.1.5
    retry: ^3.1.2
    version: ^3.0.2
    rxdart: ^0.28.0
    amazon_cognito_identity_dart_2: ^3.6.5
    flutter_web_auth: ^0.6.0
    universal_html: ^2.2.4
    google_sign_in_web: ^0.12.4+2
    url_strategy: ^0.3.0
    crypto: ^3.0.5
    animated_custom_dropdown: ^3.1.1
    keyboard_height_plugin: ^0.1.5
    flutter_animation_progress_bar: ^2.3.1
    qr_flutter: ^4.1.0
    universal_io: ^2.2.2
    confetti: ^0.8.0
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0
    json_serializable: ^6.8.0
    riverpod_generator: ^2.4.0
    intl_utils: ^2.8.7
    build_runner: ^2.4.13
    custom_lint: ^0.6.4
    riverpod_lint: ^2.3.10
    change_app_package_name: ^1.3.0
    freezed: ^2.5.7
    intl_translation: ^0.20.0

flutter_intl:
    enabled: true

flutter:
    uses-material-design: true
    generate: true
    assets:
        - assets/
        - assets/images/
        - assets/images/login/
        - assets/icons/
        - assets/icons/login/
        - assets/icons/vote/
        - assets/icons/header/
        - assets/icons/bottom/
        - assets/icons/store/
        - assets/icons/post/
        - assets/mockup/
        - assets/mockup/my/
        - assets/mockup/gallery/
        - assets/mockup/pic/
        - assets/landing/
        - assets/web/
        - config/
    fonts:
        -   family: Pretendard
            fonts:
                -   asset: assets/fonts/Pretendard/Pretendard-ExtraLight.otf
                    weight: 100
                -   asset: assets/fonts/Pretendard/Pretendard-Thin.otf
                    weight: 200
                -   asset: assets/fonts/Pretendard/Pretendard-Light.otf
                    weight: 300
                -   asset: assets/fonts/Pretendard/Pretendard-Regular.otf
                    weight: 400
                -   asset: assets/fonts/Pretendard/Pretendard-Medium.otf
                    weight: 500
                -   asset: assets/fonts/Pretendard/Pretendard-SemiBold.otf
                    weight: 600
                -   asset: assets/fonts/Pretendard/Pretendard-Bold.otf
                    weight: 700
                -   asset: assets/fonts/Pretendard/Pretendard-ExtraBold.otf
                    weight: 800
                -   asset: assets/fonts/Pretendard/Pretendard-Black.otf
                    weight: 900

