name: picnic_app
description: "Picnic App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.44+114311

environment:
    sdk: '>=3.3.1 <4.0.0'

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    cupertino_icons: ^1.0.2
    picnic_lib:
        path: ../picnic_lib
    intl: ^0.20.2
    screen_protector: ^1.4.2+1
    supabase_flutter: ^2.8.4
    universal_platform: ^1.1.0
    flutter_screenutil: ^5.9.3
    overlay_support: ^2.1.0
    flutter_riverpod: ^2.6.1
    app_links: ^6.3.3
    another_flutter_splash_screen: ^1.2.1
    device_info_plus: ^11.2.0
    firebase_core: ^3.9.0
    sentry_flutter: ^9.0.0
    reflectable: ^4.0.10
    firebase_analytics: ^11.3.6
    flutter_secure_storage: ^9.2.3
    timezone: ^0.10.0
    freezed_annotation: ^2.4.4
    riverpod_annotation: ^2.6.1
    supabase_extensions: ^1.0.1
    flutter_svg: ^2.0.16
    tapjoy_offerwall: ^14.3.1
    flutter_branch_sdk: ^8.3.2
    network_info_plus: ^6.1.3
    firebase_crashlytics: ^4.3.4
    crowdin_sdk: ^0.8.0
    shorebird_code_push: ^2.0.3
    stack_trace: ^1.11.1
    flutter_native_splash: ^2.4.6
    flutter_phoenix: ^1.1.1
    
dev_dependencies:
    build_runner: ^2.4.13
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0
    json_serializable: ^6.9.0
    freezed: ^2.5.7
    riverpod_generator: ^2.6.3
    riverpod_lint: ^2.6.3
    flutter_launcher_icons: ^0.14.2

flutter_intl:
    enabled: false

dependency_overrides:

flutter:
    uses-material-design: true
    generate: true
    assets:
        - config/
        - assets/login/
        - assets/splash.webp
        - assets/app_icon_128.png
        - shorebird.yaml
