#!/usr/bin/env python3
"""Generates picnic_lib/test/helpers/longest_app_localizations.dart.

The "longest" pseudo-locale answers every l10n key with the translation that
takes the most room among all shipped locales. Layout tests use it to check a
screen against the worst string length without running all 14 locales.

Run from the repo root after changing any arb file:
    python3 scripts/i18n/gen_longest_l10n.py

Width is estimated, not measured: full-width scripts (Hangul, CJK) count
1.0 em per character and everything else 0.55 em.

Thai, Burmese and Bengali are NOT candidates by default. Tests only load
Pretendard, so those scripts render with a box font where every code point —
combining marks included — is one em wide. Real glyphs are far narrower, so a
"longest" locale drawn from them would test the box font, not the app: with
them included, 582 of 623 keys came from those three locales. Pass
--include-box-scripts to get that stricter variant anyway (for instance after
adding Noto fonts to the test assets).
"""
import io
import json
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'picnic_lib')
L10N = os.path.join(ROOT, 'lib', 'l10n')
OUT = os.path.join(ROOT, 'test', 'helpers', 'longest_app_localizations.dart')

# locale -> (generated class suffix, generated file suffix)
LOCALES = {
    'en': ('En', 'en'), 'bn': ('Bn', 'bn'), 'bn_BD': ('BnBd', 'bn'),
    'es': ('Es', 'es'), 'fil': ('Fil', 'fil'), 'ja': ('Ja', 'ja'),
    'id': ('Id', 'id'), 'ko': ('Ko', 'ko'), 'vi': ('Vi', 'vi'),
    'my': ('My', 'my'), 'th': ('Th', 'th'), 'zh': ('Zh', 'zh'),
    'zh_CN': ('ZhCn', 'zh'), 'zh_TW': ('ZhTw', 'zh'),
}


BOX_FONT_LOCALES = {'th', 'my', 'bn', 'bn_BD'}


def wide(ch):
    o = ord(ch)
    return (
        0x1100 <= o <= 0x11FF or 0x2E80 <= o <= 0x9FFF or 0xAC00 <= o <= 0xD7AF
        or 0xF900 <= o <= 0xFAFF or 0xFF00 <= o <= 0xFFEF
        or 0x0E00 <= o <= 0x0E7F      # Thai
        or 0x1000 <= o <= 0x109F      # Myanmar
        or 0x0980 <= o <= 0x09FF      # Bengali
    )


def width(text):
    # Placeholders are replaced at runtime; their own length is not the point.
    text = re.sub(r'\{[^{}]*\}', 'xx', text)
    return sum(1.0 if wide(c) else 0.55 for c in text)


def main():
    src = io.open(os.path.join(L10N, 'app_localizations.dart'), encoding='utf-8').read()
    getters = re.findall(r'\n  String get (\w+);', src)
    methods = re.findall(r'\n  String (\w+)\(([^;]*?)\);', src, re.S)

    arbs = {}
    for loc in LOCALES:
        data = json.load(io.open(os.path.join(L10N, f'app_{loc}.arb'), encoding='utf-8'))
        arbs[loc] = {k: v for k, v in data.items()
                     if not k.startswith('@') and isinstance(v, str)}

    include_box = '--include-box-scripts' in sys.argv
    candidates = [l for l in LOCALES if include_box or l not in BOX_FONT_LOCALES]

    def pick(key):
        best, best_w = 'en', -1.0
        for loc in candidates:  # list order makes ties deterministic
            value = arbs[loc].get(key)
            if value is None:
                continue
            w = width(value)
            if w > best_w:
                best, best_w = loc, w
        return best

    used, body, counts = set(), [], {}
    for key in getters:
        loc = pick(key)
        used.add(loc)
        counts[loc] = counts.get(loc, 0) + 1
        body.append(f'  @override\n  String get {key} => _{loc}.{key};\n')
    for key, params in methods:
        loc = pick(key)
        used.add(loc)
        counts[loc] = counts.get(loc, 0) + 1
        params = ' '.join(params.split()).rstrip(',')
        names = [p.strip().split(' ')[-1] for p in params.split(',') if p.strip()]
        body.append(f'  @override\n  String {key}({params}) =>\n'
                    f'      _{loc}.{key}({", ".join(names)});\n')

    out = [
        '// GENERATED by scripts/i18n/gen_longest_l10n.py — do not edit by hand.\n',
        '//\n',
        '// Every key answers with the translation that takes the most room among the\n',
        '// shipped locales. See the generator for how "most room" is estimated.\n',
        '// ignore_for_file: non_constant_identifier_names\n\n',
        "import 'package:flutter/widgets.dart';\n",
        "import 'package:picnic_lib/l10n/app_localizations.dart';\n",
    ]
    for f in sorted({LOCALES[l][1] for l in used}):
        out.append(f"import 'package:picnic_lib/l10n/app_localizations_{f}.dart';\n")
    out.append('\nclass LongestAppLocalizations extends AppLocalizations {\n')
    out.append("  LongestAppLocalizations() : super('en');\n\n")
    for loc in sorted(used):
        out.append(f'  static final _{loc} = AppLocalizations{LOCALES[loc][0]}();\n')
    out.append('\n' + '\n'.join(body) + '}\n\n')
    out.append(
        '/// Serves [LongestAppLocalizations] for whatever locale the app asks for.\n'
        'class LongestAppLocalizationsDelegate\n'
        '    extends LocalizationsDelegate<AppLocalizations> {\n'
        '  const LongestAppLocalizationsDelegate();\n\n'
        '  @override\n  bool isSupported(Locale locale) => true;\n\n'
        '  @override\n  Future<AppLocalizations> load(Locale locale) async =>\n'
        '      LongestAppLocalizations();\n\n'
        '  @override\n  bool shouldReload(LongestAppLocalizationsDelegate old) => false;\n'
        '}\n'
    )
    io.open(OUT, 'w', encoding='utf-8').write(''.join(out))
    print(f'{len(getters)} getters, {len(methods)} methods -> {os.path.relpath(OUT)}')
    print('source locale share:', dict(sorted(counts.items(), key=lambda kv: -kv[1])))


if __name__ == '__main__':
    sys.exit(main())
