import 'package:flutter/material.dart';
import 'package:picnic_app/generated/l10n.dart';

class PoeticMessages {
  static String get(BuildContext context, int score) {
    switch (score) {
      case 0:
        return S.of(context).poetic_0;
      case 1:
        return S.of(context).poetic_1;
      case 2:
        return S.of(context).poetic_2;
      case 3:
        return S.of(context).poetic_3;
      case 4:
        return S.of(context).poetic_4;
      case 5:
        return S.of(context).poetic_5;
      case 6:
        return S.of(context).poetic_6;
      case 7:
        return S.of(context).poetic_7;
      case 8:
        return S.of(context).poetic_8;
      case 9:
        return S.of(context).poetic_9;
      case 10:
        return S.of(context).poetic_10;
      case 11:
        return S.of(context).poetic_11;
      case 12:
        return S.of(context).poetic_12;
      case 13:
        return S.of(context).poetic_13;
      case 14:
        return S.of(context).poetic_14;
      case 15:
        return S.of(context).poetic_15;
      case 16:
        return S.of(context).poetic_16;
      case 17:
        return S.of(context).poetic_17;
      case 18:
        return S.of(context).poetic_18;
      case 19:
        return S.of(context).poetic_19;
      case 20:
        return S.of(context).poetic_20;
      case 21:
        return S.of(context).poetic_21;
      case 22:
        return S.of(context).poetic_22;
      case 23:
        return S.of(context).poetic_23;
      case 24:
        return S.of(context).poetic_24;
      case 25:
        return S.of(context).poetic_25;
      case 26:
        return S.of(context).poetic_26;
      case 27:
        return S.of(context).poetic_27;
      case 28:
        return S.of(context).poetic_28;
      case 29:
        return S.of(context).poetic_29;
      case 30:
        return S.of(context).poetic_30;
      case 31:
        return S.of(context).poetic_31;
      case 32:
        return S.of(context).poetic_32;
      case 33:
        return S.of(context).poetic_33;
      case 34:
        return S.of(context).poetic_34;
      case 35:
        return S.of(context).poetic_35;
      case 36:
        return S.of(context).poetic_36;
      case 37:
        return S.of(context).poetic_37;
      case 38:
        return S.of(context).poetic_38;
      case 39:
        return S.of(context).poetic_39;
      case 40:
        return S.of(context).poetic_40;
      case 41:
        return S.of(context).poetic_41;
      case 42:
        return S.of(context).poetic_42;
      case 43:
        return S.of(context).poetic_43;
      case 44:
        return S.of(context).poetic_44;
      case 45:
        return S.of(context).poetic_45;
      case 46:
        return S.of(context).poetic_46;
      case 47:
        return S.of(context).poetic_47;
      case 48:
        return S.of(context).poetic_48;
      case 49:
        return S.of(context).poetic_49;
      case 50:
        return S.of(context).poetic_50;
      case 51:
        return S.of(context).poetic_51;
      case 52:
        return S.of(context).poetic_52;
      case 53:
        return S.of(context).poetic_53;
      case 54:
        return S.of(context).poetic_54;
      case 55:
        return S.of(context).poetic_55;
      case 56:
        return S.of(context).poetic_56;
      case 57:
        return S.of(context).poetic_57;
      case 58:
        return S.of(context).poetic_58;
      case 59:
        return S.of(context).poetic_59;
      case 60:
        return S.of(context).poetic_60;
      case 61:
        return S.of(context).poetic_61;
      case 62:
        return S.of(context).poetic_62;
      case 63:
        return S.of(context).poetic_63;
      case 64:
        return S.of(context).poetic_64;
      case 65:
        return S.of(context).poetic_65;
      case 66:
        return S.of(context).poetic_66;
      case 67:
        return S.of(context).poetic_67;
      case 68:
        return S.of(context).poetic_68;
      case 69:
        return S.of(context).poetic_69;
      case 70:
        return S.of(context).poetic_70;
      case 71:
        return S.of(context).poetic_71;
      case 72:
        return S.of(context).poetic_72;
      case 73:
        return S.of(context).poetic_73;
      case 74:
        return S.of(context).poetic_74;
      case 75:
        return S.of(context).poetic_75;
      case 76:
        return S.of(context).poetic_76;
      case 77:
        return S.of(context).poetic_77;
      case 78:
        return S.of(context).poetic_78;
      case 79:
        return S.of(context).poetic_79;
      case 80:
        return S.of(context).poetic_80;
      case 81:
        return S.of(context).poetic_81;
      case 82:
        return S.of(context).poetic_82;
      case 83:
        return S.of(context).poetic_83;
      case 84:
        return S.of(context).poetic_84;
      case 85:
        return S.of(context).poetic_85;
      case 86:
        return S.of(context).poetic_86;
      case 87:
        return S.of(context).poetic_87;
      case 88:
        return S.of(context).poetic_88;
      case 89:
        return S.of(context).poetic_89;
      case 90:
        return S.of(context).poetic_90;
      case 91:
        return S.of(context).poetic_91;
      case 92:
        return S.of(context).poetic_92;
      case 93:
        return S.of(context).poetic_93;
      case 94:
        return S.of(context).poetic_94;
      case 95:
        return S.of(context).poetic_95;
      case 96:
        return S.of(context).poetic_96;
      case 97:
        return S.of(context).poetic_97;
      case 98:
        return S.of(context).poetic_98;
      case 99:
        return S.of(context).poetic_99;
      case 100:
        return S.of(context).poetic_100;
      default:
        return '';
    }
  }
}
