// GENERATED by scripts/i18n/gen_longest_l10n.py — do not edit by hand.
//
// Every key answers with the translation that takes the most room among the
// shipped locales. See the generator for how "most room" is estimated.
//
// It extends the English class, so a key added to the arb files after this
// was generated still compiles (it answers in English). A test compares
// [longestArbChecksum] with the arb files and asks for a regeneration.
// ignore_for_file: non_constant_identifier_names

import 'package:flutter/widgets.dart';
import 'package:picnic_lib/l10n/app_localizations.dart';
import 'package:picnic_lib/l10n/app_localizations_en.dart';
import 'package:picnic_lib/l10n/app_localizations_es.dart';
import 'package:picnic_lib/l10n/app_localizations_fil.dart';
import 'package:picnic_lib/l10n/app_localizations_id.dart';
import 'package:picnic_lib/l10n/app_localizations_ja.dart';
import 'package:picnic_lib/l10n/app_localizations_ko.dart';
import 'package:picnic_lib/l10n/app_localizations_vi.dart';

/// FNV-1a 32 of the arb files this was generated from.
const int longestArbChecksum = 0x9C59013E;

class LongestAppLocalizations extends AppLocalizationsEn {
  LongestAppLocalizations() : super('en');

  static final _es = AppLocalizationsEs();
  static final _fil = AppLocalizationsFil();
  static final _id = AppLocalizationsId();
  static final _ja = AppLocalizationsJa();
  static final _ko = AppLocalizationsKo();
  static final _vi = AppLocalizationsVi();

  @override
  String get achieve => _id.achieve;

  @override
  String get ads_available_time => _fil.ads_available_time;

  @override
  String get anonymous_mode => _fil.anonymous_mode;

  @override
  String get block_user_label => _fil.block_user_label;

  @override
  String get button_cancel => _fil.button_cancel;

  @override
  String get button_complete => _fil.button_complete;

  @override
  String get button_login => _es.button_login;

  @override
  String get button_ok => _fil.button_ok;

  @override
  String get comments => _fil.comments;

  @override
  String get common_all => _vi.common_all;

  @override
  String get common_fail => _vi.common_fail;

  @override
  String get common_retry_label => _es.common_retry_label;

  @override
  String get common_success => _vi.common_success;

  @override
  String get common_text_no_data => _id.common_text_no_data;

  @override
  String get common_text_no_search_result => _fil.common_text_no_search_result;

  @override
  String get common_text_search_error => _vi.common_text_search_error;

  @override
  String get common_text_search_recent_label =>
      _fil.common_text_search_recent_label;

  @override
  String get common_text_search_result_label =>
      _es.common_text_search_result_label;

  @override
  String get goonghap_activities_title => _fil.goonghap_activities_title;

  @override
  String get goonghap_artist_no_birthdate => _es.goonghap_artist_no_birthdate;

  @override
  String get goonghap_agree_checkbox => _fil.goonghap_agree_checkbox;

  @override
  String get goonghap_analyze_start => _fil.goonghap_analyze_start;

  @override
  String get goonghap_analyzing => _ja.goonghap_analyzing;

  @override
  String get goonghap_analyzing_prepare => _id.goonghap_analyzing_prepare;

  @override
  String get goonghap_birthday => _fil.goonghap_birthday;

  @override
  String get goonghap_birthtime => _fil.goonghap_birthtime;

  @override
  String get goonghap_couple_style => _fil.goonghap_couple_style;

  @override
  String get goonghap_duplicate_data_title =>
      _fil.goonghap_duplicate_data_title;

  @override
  String get goonghap_gender => _id.goonghap_gender;

  @override
  String get goonghap_gender_female => _id.goonghap_gender_female;

  @override
  String get goonghap_gender_male => _es.goonghap_gender_male;

  @override
  String get goonghap_idol_style => _vi.goonghap_idol_style;

  @override
  String get goonghap_new => _fil.goonghap_new;

  @override
  String get goonghap_purchase_confirm_message =>
      _es.goonghap_purchase_confirm_message;

  @override
  String get goonghap_remain_star_candy => _es.goonghap_remain_star_candy;

  @override
  String get goonghap_result_not_found => _vi.goonghap_result_not_found;

  @override
  String get goonghap_share_hashtag => _ja.goonghap_share_hashtag;

  @override
  String get goonghap_snackbar_error => _fil.goonghap_snackbar_error;

  @override
  String get goonghap_snackbar_need_gender =>
      _fil.goonghap_snackbar_need_gender;

  @override
  String get goonghap_snackbar_start => _fil.goonghap_snackbar_start;

  @override
  String get goonghap_style_title => _fil.goonghap_style_title;

  @override
  String get goonghap_time_slot10 => _vi.goonghap_time_slot10;

  @override
  String get goonghap_time_slot12 => _fil.goonghap_time_slot12;

  @override
  String get goonghap_time_slot6 => _es.goonghap_time_slot6;

  @override
  String get goonghap_tips_title => _es.goonghap_tips_title;

  @override
  String get goonghap_user_style => _fil.goonghap_user_style;

  @override
  String get goonghap_waiting_message => _fil.goonghap_waiting_message;

  @override
  String get goonghap_warning_exit => _vi.goonghap_warning_exit;

  @override
  String get dialog_button_cancel => _fil.dialog_button_cancel;

  @override
  String get dialog_button_ok => _fil.dialog_button_ok;

  @override
  String get dialog_caution => _ja.dialog_caution;

  @override
  String get dialog_content_ads_exhausted => _es.dialog_content_ads_exhausted;

  @override
  String get dialog_content_login_required =>
      _fil.dialog_content_login_required;

  @override
  String get dialog_message_can_resignup => _vi.dialog_message_can_resignup;

  @override
  String get dialog_message_purchase_failed =>
      _fil.dialog_message_purchase_failed;

  @override
  String get dialog_message_purchase_success =>
      _vi.dialog_message_purchase_success;

  @override
  String get dialog_title_ads_exhausted => _fil.dialog_title_ads_exhausted;

  @override
  String get dialog_title_vote_fail => _id.dialog_title_vote_fail;

  @override
  String get dialog_will_delete_star_candy => _es.dialog_will_delete_star_candy;

  @override
  String get dialog_withdraw_message => _fil.dialog_withdraw_message;

  @override
  String get dialog_withdraw_title => _fil.dialog_withdraw_title;

  @override
  String get error_action_failed => _fil.error_action_failed;

  @override
  String get error_content_parse => _fil.error_content_parse;

  @override
  String get error_invalid_data => _vi.error_invalid_data;

  @override
  String get error_network_connection => _fil.error_network_connection;

  @override
  String get error_request_timeout => _es.error_request_timeout;

  @override
  String get error_title => _fil.error_title;

  @override
  String get error_unknown => _fil.error_unknown;

  @override
  String get faq_category_all => _vi.faq_category_all;

  @override
  String get fortune_advice => _vi.fortune_advice;

  @override
  String get fortune_button_title => _vi.fortune_button_title;

  @override
  String get fortune_career => _es.fortune_career;

  @override
  String get fortune_health => _fil.fortune_health;

  @override
  String get fortune_honor => _fil.fortune_honor;

  @override
  String get fortune_lack_of_star_candy_message =>
      _fil.fortune_lack_of_star_candy_message;

  @override
  String get fortune_lack_of_star_candy_title =>
      _es.fortune_lack_of_star_candy_title;

  @override
  String get fortune_lucky_color => _id.fortune_lucky_color;

  @override
  String get fortune_lucky_days => _id.fortune_lucky_days;

  @override
  String get fortune_lucky_keyword => _es.fortune_lucky_keyword;

  @override
  String get fortune_lucky_number => _vi.fortune_lucky_number;

  @override
  String get fortune_money => _vi.fortune_money;

  @override
  String get fortune_month1 => _id.fortune_month1;

  @override
  String get fortune_month10 => _id.fortune_month10;

  @override
  String get fortune_month11 => _id.fortune_month11;

  @override
  String get fortune_month12 => _id.fortune_month12;

  @override
  String get fortune_month2 => _id.fortune_month2;

  @override
  String get fortune_month3 => _id.fortune_month3;

  @override
  String get fortune_month4 => _id.fortune_month4;

  @override
  String get fortune_month5 => _id.fortune_month5;

  @override
  String get fortune_month6 => _id.fortune_month6;

  @override
  String get fortune_month7 => _id.fortune_month7;

  @override
  String get fortune_month8 => _id.fortune_month8;

  @override
  String get fortune_month9 => _id.fortune_month9;

  @override
  String get fortune_monthly => _fil.fortune_monthly;

  @override
  String get fortune_total_title => _id.fortune_total_title;

  @override
  String get fortune_with_me => _ja.fortune_with_me;

  @override
  String get hint_library_add => _fil.hint_library_add;

  @override
  String get hint_nickname_input => _fil.hint_nickname_input;

  @override
  String get image_save_success => _es.image_save_success;

  @override
  String get label_ads_exceeded => _fil.label_ads_exceeded;

  @override
  String get label_ads_get_star_candy => _fil.label_ads_get_star_candy;

  @override
  String get label_ads_get_cotton_candy => _es.label_ads_get_cotton_candy;

  @override
  String get label_ads_load_fail => _es.label_ads_load_fail;

  @override
  String get label_ads_temporarily_unavailable =>
      _fil.label_ads_temporarily_unavailable;

  @override
  String get label_ads_sdk_init_fail => _es.label_ads_sdk_init_fail;

  @override
  String get label_ads_show_fail => _fil.label_ads_show_fail;

  @override
  String get label_agreement_privacy => _es.label_agreement_privacy;

  @override
  String get label_agreement_terms => _fil.label_agreement_terms;

  @override
  String get label_album_add => _fil.label_album_add;

  @override
  String get label_article_comment_empty => _ja.label_article_comment_empty;

  @override
  String get label_asia_recommendation => _ja.label_asia_recommendation;

  @override
  String get label_bonus => _es.label_bonus;

  @override
  String get label_button_agreement => _fil.label_button_agreement;

  @override
  String get label_button_close => _fil.label_button_close;

  @override
  String get label_button_recharge => _id.label_button_recharge;

  @override
  String get label_button_view_policy => _fil.label_button_view_policy;

  @override
  String get label_button_vote => _vi.label_button_vote;

  @override
  String get label_celeb_gallery => _vi.label_celeb_gallery;

  @override
  String get label_celeb_recommend => _es.label_celeb_recommend;

  @override
  String get label_checkbox_entire_use => _id.label_checkbox_entire_use;

  @override
  String get label_draw_image => _fil.label_draw_image;

  @override
  String get label_dropdown_oldest => _vi.label_dropdown_oldest;

  @override
  String get label_dropdown_recent => _es.label_dropdown_recent;

  @override
  String get label_global_recommendation => _fil.label_global_recommendation;

  @override
  String get label_hint_comment => _ja.label_hint_comment;

  @override
  String get label_home_current_vote => _id.label_home_current_vote;

  @override
  String get label_input_input => _id.label_input_input;

  @override
  String get label_korean_recommendation => _es.label_korean_recommendation;

  @override
  String get label_last_provider => _fil.label_last_provider;

  @override
  String get label_library_save => _id.label_library_save;

  @override
  String get label_library_tab_ai_photo => _fil.label_library_tab_ai_photo;

  @override
  String get label_library_tab_library => _id.label_library_tab_library;

  @override
  String get label_library_tab_pic => _ja.label_library_tab_pic;

  @override
  String get label_loading_ads => _vi.label_loading_ads;

  @override
  String get label_mission_get_star_candy => _fil.label_mission_get_star_candy;

  @override
  String get label_mission_get_bonus_star_candy =>
      _es.label_mission_get_bonus_star_candy;

  @override
  String get label_mission_short => _ja.label_mission_short;

  @override
  String get label_moveto_celeb_gallery => _vi.label_moveto_celeb_gallery;

  @override
  String get label_mypage_faq => _id.label_mypage_faq;

  @override
  String get label_mypage_logout => _es.label_mypage_logout;

  @override
  String get label_mypage_my_artist => _fil.label_mypage_my_artist;

  @override
  String get label_mypage_no_artist => _ja.label_mypage_no_artist;

  @override
  String get label_mypage_notice => _id.label_mypage_notice;

  @override
  String get label_mypage_notifications => _es.label_mypage_notifications;

  @override
  String get label_mypage_picnic_id => _ja.label_mypage_picnic_id;

  @override
  String get label_mypage_privacy_policy => _fil.label_mypage_privacy_policy;

  @override
  String get label_mypage_setting => _es.label_mypage_setting;

  @override
  String get label_mypage_should_login => _es.label_mypage_should_login;

  @override
  String get label_mypage_terms_of_use => _fil.label_mypage_terms_of_use;

  @override
  String get label_mypage_vote_history => _fil.label_mypage_vote_history;

  @override
  String get label_no_celeb => _vi.label_no_celeb;

  @override
  String get label_pic_chart => _es.label_pic_chart;

  @override
  String get label_pic_pic_save_gallery => _es.label_pic_pic_save_gallery;

  @override
  String get label_read_more_comment => _fil.label_read_more_comment;

  @override
  String get label_reply => _es.label_reply;

  @override
  String get label_retry => _es.label_retry;

  @override
  String get label_setting_alarm => _es.label_setting_alarm;

  @override
  String get label_setting_appinfo => _es.label_setting_appinfo;

  @override
  String get label_setting_current_version =>
      _fil.label_setting_current_version;

  @override
  String get label_setting_event_alarm => _es.label_setting_event_alarm;

  @override
  String get label_setting_event_alarm_desc =>
      _ja.label_setting_event_alarm_desc;

  @override
  String get label_setting_language => _es.label_setting_language;

  @override
  String get label_setting_push_alarm => _es.label_setting_push_alarm;

  @override
  String get label_setting_recent_version => _fil.label_setting_recent_version;

  @override
  String get label_setting_recent_version_up_to_date =>
      _fil.label_setting_recent_version_up_to_date;

  @override
  String get label_setting_remove_cache => _fil.label_setting_remove_cache;

  @override
  String get label_setting_storage => _es.label_setting_storage;

  @override
  String get label_star_candy_pouch => _id.label_star_candy_pouch;

  @override
  String get label_tabbar_vote_active => _id.label_tabbar_vote_active;

  @override
  String get label_tabbar_vote_end => _es.label_tabbar_vote_end;

  @override
  String get label_time_ago_right_now => _id.label_time_ago_right_now;

  @override
  String get label_title_report => _fil.label_title_report;

  @override
  String get label_unlimited_rewards => _fil.label_unlimited_rewards;

  @override
  String get label_vote_end => _vi.label_vote_end;

  @override
  String get label_vote_reward_list => _fil.label_vote_reward_list;

  @override
  String get label_vote_screen_title => _id.label_vote_screen_title;

  @override
  String get label_vote_upcoming => _fil.label_vote_upcoming;

  @override
  String get label_watch_ads_short => _fil.label_watch_ads_short;

  @override
  String get lable_my_celeb => _fil.lable_my_celeb;

  @override
  String get message_error_occurred => _fil.message_error_occurred;

  @override
  String get message_noitem_vote_active => _id.message_noitem_vote_active;

  @override
  String get message_noitem_vote_end => _fil.message_noitem_vote_end;

  @override
  String get message_noitem_vote_upcoming => _id.message_noitem_vote_upcoming;

  @override
  String get message_pic_pic_save_fail => _fil.message_pic_pic_save_fail;

  @override
  String get message_pic_pic_save_success => _es.message_pic_pic_save_success;

  @override
  String get message_store_products_load_failed =>
      _es.message_store_products_load_failed;

  @override
  String get message_vote_is_ended => _vi.message_vote_is_ended;

  @override
  String get message_vote_is_upcoming => _id.message_vote_is_upcoming;

  @override
  String get my_info => _fil.my_info;

  @override
  String get mypage_setting => _es.mypage_setting;

  @override
  String get nav_media => _vi.nav_media;

  @override
  String get nickname_validation_error => _fil.nickname_validation_error;

  @override
  String get page_title_mypage => _fil.page_title_mypage;

  @override
  String get page_title_post_write => _es.page_title_post_write;

  @override
  String get page_title_vote_detail => _vi.page_title_vote_detail;

  @override
  String get popup_label_delete => _fil.popup_label_delete;

  @override
  String get post_anonymous => _fil.post_anonymous;

  @override
  String get post_board_create_request_complete =>
      _fil.post_board_create_request_complete;

  @override
  String get post_board_create_request_condition =>
      _fil.post_board_create_request_condition;

  @override
  String get post_board_request_label => _fil.post_board_request_label;

  @override
  String get post_comment_content_more => _id.post_comment_content_more;

  @override
  String get post_comment_delete_confirm => _es.post_comment_delete_confirm;

  @override
  String get post_comment_delete_fail => _es.post_comment_delete_fail;

  @override
  String get post_comment_deleted_comment => _id.post_comment_deleted_comment;

  @override
  String get post_comment_like_processing_fail =>
      _fil.post_comment_like_processing_fail;

  @override
  String get post_comment_loading_fail => _fil.post_comment_loading_fail;

  @override
  String get post_comment_register_fail => _fil.post_comment_register_fail;

  @override
  String get post_comment_reported_comment => _id.post_comment_reported_comment;

  @override
  String get post_comment_translate_fail => _vi.post_comment_translate_fail;

  @override
  String get post_comment_translated => _id.post_comment_translated;

  @override
  String get post_comment_write_label => _es.post_comment_write_label;

  @override
  String get post_content_placeholder => _fil.post_content_placeholder;

  @override
  String get post_delete_scrap_confirm => _fil.post_delete_scrap_confirm;

  @override
  String get post_delete_scrap_title => _fil.post_delete_scrap_title;

  @override
  String get post_flagged => _fil.post_flagged;

  @override
  String get post_go_to_boards => _id.post_go_to_boards;

  @override
  String get post_header_publish => _fil.post_header_publish;

  @override
  String get post_header_temporary_save => _vi.post_header_temporary_save;

  @override
  String get post_hint_title => _fil.post_hint_title;

  @override
  String get post_hyperlink => _es.post_hyperlink;

  @override
  String get post_insert_link => _es.post_insert_link;

  @override
  String get post_minor_board_condition => _fil.post_minor_board_condition;

  @override
  String get post_minor_board_description => _fil.post_minor_board_description;

  @override
  String get post_minor_board_description_input =>
      _fil.post_minor_board_description_input;

  @override
  String get post_minor_board_name => _fil.post_minor_board_name;

  @override
  String get post_minor_board_name_input => _fil.post_minor_board_name_input;

  @override
  String get post_my_compatibilities => _fil.post_my_compatibilities;

  @override
  String get post_my_written_post => _id.post_my_written_post;

  @override
  String get post_my_written_reply => _fil.post_my_written_reply;

  @override
  String get post_my_written_scrap => _fil.post_my_written_scrap;

  @override
  String get post_no_comment => _ja.post_no_comment;

  @override
  String get post_not_found => _vi.post_not_found;

  @override
  String get post_deleted_title => _es.post_deleted_title;

  @override
  String get post_deleted_desc => _es.post_deleted_desc;

  @override
  String get post_report_fail => _id.post_report_fail;

  @override
  String get post_report_label => _fil.post_report_label;

  @override
  String get post_report_other_input => _fil.post_report_other_input;

  @override
  String get post_report_reason_1 => _id.post_report_reason_1;

  @override
  String get post_report_reason_2 => _vi.post_report_reason_2;

  @override
  String get post_report_reason_3 => _id.post_report_reason_3;

  @override
  String get post_report_reason_4 => _es.post_report_reason_4;

  @override
  String get post_report_reason_5 => _id.post_report_reason_5;

  @override
  String get post_report_reason_input => _fil.post_report_reason_input;

  @override
  String get post_report_reason_label => _fil.post_report_reason_label;

  @override
  String get post_report_success => _es.post_report_success;

  @override
  String get post_title_placeholder => _fil.post_title_placeholder;

  @override
  String get post_youtube_link => _es.post_youtube_link;

  @override
  String get purchase_confirm_title => _es.purchase_confirm_title;

  @override
  String get previousTransactionPendingError =>
      _fil.previousTransactionPendingError;

  @override
  String get purchase_in_progress_message => _fil.purchase_in_progress_message;

  @override
  String get purchase_initializing_message =>
      _fil.purchase_initializing_message;

  @override
  String get purchase_payment_amount => _fil.purchase_payment_amount;

  @override
  String get purchase_web_message => _es.purchase_web_message;

  @override
  String get qna_content => _es.qna_content;

  @override
  String get qna_create_page_title => _fil.qna_create_page_title;

  @override
  String get qna_no_inquiries => _fil.qna_no_inquiries;

  @override
  String get qna_status_closed => _es.qna_status_closed;

  @override
  String get qna_status_open => _es.qna_status_open;

  @override
  String get qna_submit_button => _fil.qna_submit_button;

  @override
  String get qna_title => _ja.qna_title;

  @override
  String get replies => _fil.replies;

  @override
  String get reward => _es.reward;

  @override
  String get save => _es.save;

  @override
  String get seconds => _es.seconds;

  @override
  String get share => _es.share;

  @override
  String get text_community_board_search => _es.text_community_board_search;

  @override
  String get text_community_post_search => _id.text_community_post_search;

  @override
  String get text_copied => _ko.text_copied;

  @override
  String get ban_support_instruction => _es.ban_support_instruction;

  @override
  String get action_copy => _fil.action_copy;

  @override
  String get text_draw_image => _id.text_draw_image;

  @override
  String get text_hint_search => _fil.text_hint_search;

  @override
  String get text_moveto_celeb_gallery => _es.text_moveto_celeb_gallery;

  @override
  String get text_need_recharge => _fil.text_need_recharge;

  @override
  String get text_no_search_result => _fil.text_no_search_result;

  @override
  String get text_purchase_vat_included => _fil.text_purchase_vat_included;

  @override
  String get text_vote_complete => _id.text_vote_complete;

  @override
  String get text_vote_rank_in_reward => _id.text_vote_rank_in_reward;

  @override
  String get text_vote_where_is_my_bias => _es.text_vote_where_is_my_bias;

  @override
  String get title_dialog_library_add => _fil.title_dialog_library_add;

  @override
  String get title_select_language => _es.title_select_language;

  @override
  String get toast_bookmark_added => _fil.toast_bookmark_added;

  @override
  String get toast_bookmark_removed => _fil.toast_bookmark_removed;

  @override
  String get toast_max_five_celeb => _fil.toast_max_five_celeb;

  @override
  String get update_button => _id.update_button;

  @override
  String get update_cannot_open_appstore => _id.update_cannot_open_appstore;

  @override
  String get update_required_title => _fil.update_required_title;

  @override
  String get views => _vi.views;

  @override
  String get vote_item_request_can_apply => _fil.vote_item_request_can_apply;

  @override
  String get vote_item_request_search_artist =>
      _es.vote_item_request_search_artist;

  @override
  String get vote_item_request_status => _fil.vote_item_request_status;

  @override
  String get vote_item_request_status_approved =>
      _fil.vote_item_request_status_approved;

  @override
  String get vote_item_request_status_pending =>
      _vi.vote_item_request_status_pending;

  @override
  String get vote_item_request_status_rejected =>
      _vi.vote_item_request_status_rejected;

  @override
  String get vote_item_request_submit => _es.vote_item_request_submit;

  @override
  String get vote_item_request_title => _id.vote_item_request_title;

  @override
  String get vote_share_message => _ko.vote_share_message;

  @override
  String get vote_completed_message => _id.vote_completed_message;

  @override
  String get voting_share_benefit_text => _es.voting_share_benefit_text;

  @override
  String get cancel => _fil.cancel;

  @override
  String get confirm => _fil.confirm;

  @override
  String get loading => _fil.loading;

  @override
  String get retry => _id.retry;

  @override
  String get update => _es.update;

  @override
  String get ban_title => _ko.ban_title;

  @override
  String get ban_message => _fil.ban_message;

  @override
  String get ban_contact => _fil.ban_contact;

  @override
  String get goonghap_empty_state_title => _fil.goonghap_empty_state_title;

  @override
  String get goonghap_empty_state_subtitle =>
      _fil.goonghap_empty_state_subtitle;

  @override
  String get goonghap_login_required_title =>
      _fil.goonghap_login_required_title;

  @override
  String get goonghap_login_required_subtitle =>
      _fil.goonghap_login_required_subtitle;

  @override
  String get goonghap_login_button => _es.goonghap_login_button;

  @override
  String get network_error_title => _fil.network_error_title;

  @override
  String get network_error_message => _fil.network_error_message;

  @override
  String get notice_pinned => _fil.notice_pinned;

  @override
  String get title_dialog_error => _id.title_dialog_error;

  @override
  String get vote_item_request_waiting => _fil.vote_item_request_waiting;

  @override
  String get capture_failed => _ja.capture_failed;

  @override
  String get qna_submit_success => _fil.qna_submit_success;

  @override
  String get qna_list_title => _fil.qna_list_title;

  @override
  String get starCandy100 => _es.starCandy100;

  @override
  String get starCandy200 => _es.starCandy200;

  @override
  String get starCandy600 => _es.starCandy600;

  @override
  String get starCandy1000 => _es.starCandy1000;

  @override
  String get starCandy2000 => _es.starCandy2000;

  @override
  String get starCandy3000 => _es.starCandy3000;

  @override
  String get starCandy4000 => _es.starCandy4000;

  @override
  String get starCandy5000 => _es.starCandy5000;

  @override
  String get update_required_message => _es.update_required_message;

  @override
  String get vote_item_request_no_search_results =>
      _fil.vote_item_request_no_search_results;

  @override
  String get jma_voting_my_star_candy => _vi.jma_voting_my_star_candy;

  @override
  String get jma_voting_usable_jma_votes => _fil.jma_voting_usable_jma_votes;

  @override
  String get jma_voting_use_all => _fil.jma_voting_use_all;

  @override
  String get jma_voting_input_amount => _fil.jma_voting_input_amount;

  @override
  String get jma_voting_daily_limit_error => _fil.jma_voting_daily_limit_error;

  @override
  String get jma_voting_exchange_failed => _fil.jma_voting_exchange_failed;

  @override
  String get jma_voting_daily_limit_title => _fil.jma_voting_daily_limit_title;

  @override
  String get jma_voting_exchange_failed_title =>
      _es.jma_voting_exchange_failed_title;

  @override
  String get expiring_bonus_candy_guide => _fil.expiring_bonus_candy_guide;

  @override
  String get qna_form_title_hint => _fil.qna_form_title_hint;

  @override
  String get qna_form_content_hint => _fil.qna_form_content_hint;

  @override
  String get qna_attach_media => _fil.qna_attach_media;

  @override
  String get qna_submit_fail => _fil.qna_submit_fail;

  @override
  String get qna_cannot_send_message_closed =>
      _fil.qna_cannot_send_message_closed;

  @override
  String get qna_message_sent_success => _fil.qna_message_sent_success;

  @override
  String get qna_message_sent_fail => _fil.qna_message_sent_fail;

  @override
  String get qna_no_answer_yet => _ko.qna_no_answer_yet;

  @override
  String get qna_add_media_tooltip => _vi.qna_add_media_tooltip;

  @override
  String get qna_load_fail_title => _fil.qna_load_fail_title;

  @override
  String get qna_category_label => _ja.qna_category_label;

  @override
  String get qna_category_required => _ja.qna_category_required;

  @override
  String get qna_message_hint => _es.qna_message_hint;

  @override
  String get label_my_vote_history => _fil.label_my_vote_history;

  @override
  String get bonus_candy_example_2_expire => _id.bonus_candy_example_2_expire;

  @override
  String get bonus_candy_example_earn_date => _id.bonus_candy_example_earn_date;

  @override
  String get vote_item_request_status_unknown =>
      _id.vote_item_request_status_unknown;

  @override
  String get bonus_candy_expiration_policy_load_fail =>
      _es.bonus_candy_expiration_policy_load_fail;

  @override
  String get bonus_candy_example_1_expire => _id.bonus_candy_example_1_expire;

  @override
  String get vote_item_request_status_in_progress =>
      _vi.vote_item_request_status_in_progress;

  @override
  String get bonus_candy_policy_2 => _fil.bonus_candy_policy_2;

  @override
  String get label_mypage_charge_history => _es.label_mypage_charge_history;

  @override
  String get label_popup_hide_7days => _fil.label_popup_hide_7days;

  @override
  String get expiring_soon_bonus_candy => _es.expiring_soon_bonus_candy;

  @override
  String get bonus_candy_expiration_policy_earn_period =>
      _es.bonus_candy_expiration_policy_earn_period;

  @override
  String get message_setting_remove_cache => _es.message_setting_remove_cache;

  @override
  String get error_loading_more_comments => _fil.error_loading_more_comments;

  @override
  String get purchase_timeout_message => _es.purchase_timeout_message;

  @override
  String get purchase_payment_accepted_message =>
      _es.purchase_payment_accepted_message;

  @override
  String get purchase_payment_unconfirmed_message =>
      _es.purchase_payment_unconfirmed_message;

  @override
  String get purchase_payment_pending_message =>
      _vi.purchase_payment_pending_message;

  @override
  String get label_tabbar_vote_upcoming => _fil.label_tabbar_vote_upcoming;

  @override
  String get bonus_candy_example_1_earn => _id.bonus_candy_example_1_earn;

  @override
  String get error_receipt_verification_failed =>
      _vi.error_receipt_verification_failed;

  @override
  String get vote_item_request_status_cancelled =>
      _ja.vote_item_request_status_cancelled;

  @override
  String get post_write_board_post => _es.post_write_board_post;

  @override
  String get bonus_candy_policy_3 => _id.bonus_candy_policy_3;

  @override
  String get message_update_nickname_fail => _fil.message_update_nickname_fail;

  @override
  String get bonus_candy_expiration_time_title =>
      _es.bonus_candy_expiration_time_title;

  @override
  String get post_comment_action_show_translation =>
      _fil.post_comment_action_show_translation;

  @override
  String get fortune_lucky_direction => _es.fortune_lucky_direction;

  @override
  String get error_message_login_failed => _es.error_message_login_failed;

  @override
  String get dialog_withdraw_button_ok => _fil.dialog_withdraw_button_ok;

  @override
  String get title_dialog_success => _vi.title_dialog_success;

  @override
  String get bonus_candy_policy_title => _fil.bonus_candy_policy_title;

  @override
  String get bonus_candy_example_expiration_date =>
      _fil.bonus_candy_example_expiration_date;

  @override
  String get label_tab_free_charge_station =>
      _fil.label_tab_free_charge_station;

  @override
  String get error_user_not_authenticated => _fil.error_user_not_authenticated;

  @override
  String get text_dialog_vote_amount_should_not_zero =>
      _fil.text_dialog_vote_amount_should_not_zero;

  @override
  String get message_agreement_success => _es.message_agreement_success;

  @override
  String get bonus_candy_earn_period_1_to_14 =>
      _ko.bonus_candy_earn_period_1_to_14;

  @override
  String get goonghap_snackbar_need_birthday =>
      _fil.goonghap_snackbar_need_birthday;

  @override
  String get error_product_not_found => _id.error_product_not_found;

  @override
  String get label_popup_close => _fil.label_popup_close;

  @override
  String get jma_voting_info_text => _id.jma_voting_info_text;

  @override
  String get vote_item_request_search_artist_hint =>
      _fil.vote_item_request_search_artist_hint;

  @override
  String get bonus_candy_expiration_month_after_next =>
      _fil.bonus_candy_expiration_month_after_next;

  @override
  String get post_comment_action_show_original =>
      _fil.post_comment_action_show_original;

  @override
  String get goonghap_snackbar_need_profile_save_agree =>
      _fil.goonghap_snackbar_need_profile_save_agree;

  @override
  String get qna_content_min_length => _fil.qna_content_min_length;

  @override
  String get post_ask_go_to_temporary_save_list =>
      _fil.post_ask_go_to_temporary_save_list;

  @override
  String get label_pic_pic_synthesizing_image =>
      _es.label_pic_pic_synthesizing_image;

  @override
  String get label_tab_buy_star_candy => _ja.label_tab_buy_star_candy;

  @override
  String get post_temporary_save_complete => _fil.post_temporary_save_complete;

  @override
  String get bonus_candy_example_title => _fil.bonus_candy_example_title;

  @override
  String get label_pic_pic_initializing_camera =>
      _id.label_pic_pic_initializing_camera;

  @override
  String get post_write_post_recommend_write =>
      _fil.post_write_post_recommend_write;

  @override
  String get jma_voting_daily_limit_exhausted =>
      _fil.jma_voting_daily_limit_exhausted;

  @override
  String get bonus_candy_policy_1 => _id.bonus_candy_policy_1;

  @override
  String get goonghap_perfect_score_exists_title =>
      _id.goonghap_perfect_score_exists_title;

  @override
  String get goonghap_duplicate_data_message =>
      _fil.goonghap_duplicate_data_message;

  @override
  String get bonus_candy_earn_period_15_to_end =>
      _fil.bonus_candy_earn_period_15_to_end;

  @override
  String get error_message_withdrawal => _fil.error_message_withdrawal;

  @override
  String get withdrawal_failed => _es.withdrawal_failed;

  @override
  String get vote_item_request_already_applied_artist =>
      _id.vote_item_request_already_applied_artist;

  @override
  String get bonus_candy_expiration_policy_expiration_date =>
      _fil.bonus_candy_expiration_policy_expiration_date;

  @override
  String get bonus_candy_example_2_earn => _id.bonus_candy_example_2_earn;

  @override
  String get message_agreement_fail => _fil.message_agreement_fail;

  @override
  String get vote_item_request_button => _fil.vote_item_request_button;

  @override
  String get bonus_candy_expiration_next_month =>
      _fil.bonus_candy_expiration_next_month;

  @override
  String get error_delete_post => _fil.error_delete_post;

  @override
  String get qna_title_min_length => _fil.qna_title_min_length;

  @override
  String get message_update_nickname_success =>
      _vi.message_update_nickname_success;

  @override
  String get goonghap_new_ask => _fil.goonghap_new_ask;

  @override
  String get button_pic_pic_save => _ja.button_pic_pic_save;

  @override
  String get goonghap_perfect_score_exists =>
      _fil.goonghap_perfect_score_exists;

  @override
  String get post_minor_board_create_request_message_input =>
      _fil.post_minor_board_create_request_message_input;

  @override
  String get fortune_purchase_by_star_candy =>
      _id.fortune_purchase_by_star_candy;

  @override
  String get post_minor_board_create_request_message_condition =>
      _fil.post_minor_board_create_request_message_condition;

  @override
  String get post_board_create_request_reviewing =>
      _fil.post_board_create_request_reviewing;

  @override
  String get post_minor_board_create_request_message =>
      _fil.post_minor_board_create_request_message;

  @override
  String get goonghap_purchase_confirm_title =>
      _fil.goonghap_purchase_confirm_title;

  @override
  String get post_board_create_request_label =>
      _fil.post_board_create_request_label;

  @override
  String get qna_status_received => _vi.qna_status_received;

  @override
  String get qna_status_in_progress => _id.qna_status_in_progress;

  @override
  String get qna_status_resolved => _vi.qna_status_resolved;

  @override
  String get ad_close_confirm_title => _es.ad_close_confirm_title;

  @override
  String get ad_more_info_button => _fil.ad_more_info_button;

  @override
  String get ad_reward_success_message => _fil.ad_reward_success_message;

  @override
  String get weekly_vote_info_title => _id.weekly_vote_info_title;

  @override
  String get weekly_vote_info_body => _fil.weekly_vote_info_body;

  @override
  String get weekly_vote_info_link => _es.weekly_vote_info_link;

  @override
  String get label_setting_patch_status_restart_required =>
      _fil.label_setting_patch_status_restart_required;

  @override
  String get label_setting_patch_status_downloaded =>
      _ko.label_setting_patch_status_downloaded;

  @override
  String get message_setting_patch_restart_hint =>
      _ja.message_setting_patch_restart_hint;

  @override
  String get message_setting_patch_restart_hint_ios =>
      _es.message_setting_patch_restart_hint_ios;

  @override
  String get message_setting_patch_update_available =>
      _ko.message_setting_patch_update_available;

  @override
  String get message_setting_patch_update_success =>
      _es.message_setting_patch_update_success;

  @override
  String get message_setting_patch_restarting =>
      _vi.message_setting_patch_restarting;

  @override
  String get message_setting_patch_status_unavailable =>
      _ko.message_setting_patch_status_unavailable;

  @override
  String get message_setting_patch_up_to_date =>
      _id.message_setting_patch_up_to_date;

  @override
  String get message_patch_download_complete =>
      _vi.message_patch_download_complete;

  @override
  String get message_patch_applied => _vi.message_patch_applied;

  @override
  String get dialog_setting_restart_title => _vi.dialog_setting_restart_title;

  @override
  String get dialog_setting_restart_body => _vi.dialog_setting_restart_body;

  @override
  String get button_restart => _vi.button_restart;

  @override
  String get button_update => _ja.button_update;

  @override
  String get notification_patch_update_ready_title =>
      _vi.notification_patch_update_ready_title;

  @override
  String get notification_patch_update_ready_body =>
      _es.notification_patch_update_ready_body;

  @override
  String get notification_patch_downloaded_title =>
      _ja.notification_patch_downloaded_title;

  @override
  String get notification_patch_downloaded_body =>
      _es.notification_patch_downloaded_body;

  @override
  String get vote_item_request_search_initial_guide =>
      _ja.vote_item_request_search_initial_guide;

  @override
  String get vote_item_request_search_try_other_keyword =>
      _fil.vote_item_request_search_try_other_keyword;

  @override
  String get goong_hap_title => _ja.goong_hap_title;

  @override
  String get goong_hap_subtitle => _fil.goong_hap_subtitle;

  @override
  String get goong_hap_tradition_title => _fil.goong_hap_tradition_title;

  @override
  String get goong_hap_tradition_desc => _fil.goong_hap_tradition_desc;

  @override
  String get goong_hap_kpop_title => _fil.goong_hap_kpop_title;

  @override
  String get goong_hap_kpop_desc => _fil.goong_hap_kpop_desc;

  @override
  String get goong_hap_fun_title => _es.goong_hap_fun_title;

  @override
  String get goong_hap_fun_desc => _id.goong_hap_fun_desc;

  @override
  String get goong_hap_notice => _fil.goong_hap_notice;

  @override
  String get goong_hap_close_button => _es.goong_hap_close_button;

  @override
  String get goong_hap_zodiac_title => _es.goong_hap_zodiac_title;

  @override
  String get goong_hap_zodiac_desc => _es.goong_hap_zodiac_desc;

  @override
  String get goong_hap_zodiac_subtitle => _es.goong_hap_zodiac_subtitle;

  @override
  String get goong_hap_zodiac_rat => _es.goong_hap_zodiac_rat;

  @override
  String get goong_hap_zodiac_ox => _fil.goong_hap_zodiac_ox;

  @override
  String get goong_hap_zodiac_tiger => _es.goong_hap_zodiac_tiger;

  @override
  String get goong_hap_zodiac_snake => _es.goong_hap_zodiac_snake;

  @override
  String get goong_hap_zodiac_horse => _es.goong_hap_zodiac_horse;

  @override
  String get goong_hap_zodiac_sheep => _es.goong_hap_zodiac_sheep;

  @override
  String get goong_hap_zodiac_dog => _es.goong_hap_zodiac_dog;

  @override
  String get goong_hap_zodiac_pig => _ja.goong_hap_zodiac_pig;

  @override
  String get patch_update_ready_title => _vi.patch_update_ready_title;

  @override
  String get patch_update_ios_message => _es.patch_update_ios_message;

  @override
  String get patch_update_android_message => _vi.patch_update_android_message;

  @override
  String get patch_button_later => _es.patch_button_later;

  @override
  String get patch_button_restart => _vi.patch_button_restart;

  @override
  String get patch_button_ok => _ko.patch_button_ok;

  @override
  String get patch_update_ios_message_detailed =>
      _es.patch_update_ios_message_detailed;

  @override
  String get patch_ios_how_to_close_title => _es.patch_ios_how_to_close_title;

  @override
  String get patch_ios_how_to_close_step1 => _es.patch_ios_how_to_close_step1;

  @override
  String get patch_ios_how_to_close_step2 => _es.patch_ios_how_to_close_step2;

  @override
  String get patch_ios_how_to_close_step3 => _es.patch_ios_how_to_close_step3;

  @override
  String get patch_button_restart_now => _vi.patch_button_restart_now;

  @override
  String get patch_button_understood => _fil.patch_button_understood;

  @override
  String get notifications_mark_all_read => _fil.notifications_mark_all_read;

  @override
  String get error_anti_abuse_ad_title => _fil.error_anti_abuse_ad_title;

  @override
  String get error_anti_abuse_ad_message => _es.error_anti_abuse_ad_message;

  @override
  String get error_anti_abuse_signup_title => _es.error_anti_abuse_signup_title;

  @override
  String get error_anti_abuse_signup_message =>
      _fil.error_anti_abuse_signup_message;

  @override
  String get error_anti_abuse_attendance_message =>
      _es.error_anti_abuse_attendance_message;

  @override
  String get error_anti_abuse_artist_request_title =>
      _es.error_anti_abuse_artist_request_title;

  @override
  String get error_anti_abuse_artist_request_message =>
      _es.error_anti_abuse_artist_request_message;

  @override
  String get button_cs_inquiry => _fil.button_cs_inquiry;

  @override
  String get wallet_star_candy => _ja.wallet_star_candy;

  @override
  String get wallet_bonus_star_candy => _ja.wallet_bonus_star_candy;

  @override
  String get bonus_star_candy_expiration_guide =>
      _vi.bonus_star_candy_expiration_guide;

  @override
  String get wallet_cotton_candy => _ja.wallet_cotton_candy;

  @override
  String get wallet_load_failed => _id.wallet_load_failed;

  @override
  String get wallet_history_title => _fil.wallet_history_title;

  @override
  String get wallet_history_empty => _es.wallet_history_empty;

  @override
  String get candy_boost_day => _ja.candy_boost_day;

  @override
  String get candy_boost_exact_double => _fil.candy_boost_exact_double;

  @override
  String get candy_boost_extra_bonus => _fil.candy_boost_extra_bonus;

  @override
  String get candy_boost_late_purchase_explanation =>
      _fil.candy_boost_late_purchase_explanation;

  @override
  String get purchase_reward_base => _vi.purchase_reward_base;

  @override
  String get purchase_reward_base_short => _fil.purchase_reward_base_short;

  @override
  String get purchase_reward_event_short => _ja.purchase_reward_event_short;

  @override
  String get purchase_reward_product_bonus => _es.purchase_reward_product_bonus;

  @override
  String get purchase_reward_event_bonus => _es.purchase_reward_event_bonus;

  @override
  String get purchase_reward_expected_total =>
      _fil.purchase_reward_expected_total;

  @override
  String get purchase_reward_total_short => _fil.purchase_reward_total_short;

  @override
  String get purchase_reward_estimate_note =>
      _fil.purchase_reward_estimate_note;

  @override
  String get ad_reward_pending => _vi.ad_reward_pending;

  @override
  String get ad_reward_granted => _ja.ad_reward_granted;

  @override
  String get ad_reward_not_granted => _es.ad_reward_not_granted;

  @override
  String get candy_reward_receipt_title => _ja.candy_reward_receipt_title;

  @override
  String get candy_reward_receipt_confirm => _fil.candy_reward_receipt_confirm;

  @override
  String get candy_reward_receipt_balance_unavailable =>
      _fil.candy_reward_receipt_balance_unavailable;

  @override
  String get cotton_candy_daily_expiry_notice =>
      _id.cotton_candy_daily_expiry_notice;

  @override
  String get expiry_quantity_currency => _id.expiry_quantity_currency;

  @override
  String get expiry_quantity_date => _es.expiry_quantity_date;

  @override
  String get expiry_quantity_amount => _es.expiry_quantity_amount;

  @override
  String get expiry_tonight_at_midnight => _es.expiry_tonight_at_midnight;

  @override
  String get expiry_policy_guide => _es.expiry_policy_guide;

  @override
  String get expiry_quantity_title => _fil.expiry_quantity_title;

  @override
  String get expiry_quantity_description => _fil.expiry_quantity_description;

  @override
  String get expiry_policy_description => _fil.expiry_policy_description;

  @override
  String get bonus_expiry_policy_summary => _fil.bonus_expiry_policy_summary;

  @override
  String goonghap_share_message(String artistName) =>
      _es.goonghap_share_message(artistName);

  @override
  String free_charge_ads_reward(String reward) =>
      _es.free_charge_ads_reward(reward);

  @override
  String label_ads_limits(int hourly, int daily) =>
      _fil.label_ads_limits(hourly, daily);

  @override
  String label_ads_limit_reached_hourly(int used, int limit) =>
      _fil.label_ads_limit_reached_hourly(used, limit);

  @override
  String label_ads_limit_reached_daily(int used, int limit) =>
      _fil.label_ads_limit_reached_daily(used, limit);

  @override
  String free_charge_mission_reward(String reward) =>
      _es.free_charge_mission_reward(reward);

  @override
  String label_time_ago_day(int day) => _id.label_time_ago_day(day);

  @override
  String label_time_ago_hour(int hour) => _fil.label_time_ago_hour(hour);

  @override
  String text_vote_gap_behind_leader(String gap) =>
      _es.text_vote_gap_behind_leader(gap);

  @override
  String text_vote_rank(int rank) => _vi.text_vote_rank(rank);

  @override
  String file_too_large_message(String fileName, int maxSize) =>
      _fil.file_too_large_message(fileName, maxSize);

  @override
  String qna_file_size_limit_notice(int maxSize) =>
      _fil.qna_file_size_limit_notice(maxSize);

  @override
  String goonghap_purchase_message(String artistName) =>
      _fil.goonghap_purchase_message(artistName);

  @override
  String update_recommend_text(String version) =>
      _fil.update_recommend_text(version);

  @override
  String jma_voting_max_votes_exceeded(int maxVotes) =>
      _id.jma_voting_max_votes_exceeded(maxVotes);

  @override
  String jma_voting_daily_limit_remaining(int remaining, int max) =>
      _es.jma_voting_daily_limit_remaining(remaining, max);

  @override
  String label_time_ago_minute(int minute) => _id.label_time_ago_minute(minute);

  @override
  String update_required_text(String version) =>
      _fil.update_required_text(version);

  @override
  String jma_voting_star_candy_shortage(int shortage) =>
      _fil.jma_voting_star_candy_shortage(shortage);

  @override
  String text_achievement(int count) => _fil.text_achievement(count);

  @override
  String post_replying_comment(String nickname) =>
      _es.post_replying_comment(nickname);

  @override
  String patch_auto_restart_countdown(int seconds) =>
      _fil.patch_auto_restart_countdown(seconds);

  @override
  String wallet_cotton_expires_today(String amount) =>
      _id.wallet_cotton_expires_today(amount);

  @override
  String wallet_cotton_next_expiry(String date) =>
      _id.wallet_cotton_next_expiry(date);

  @override
  String candy_boost_multiplier(String multiplier) =>
      _fil.candy_boost_multiplier(multiplier);

  @override
  String candy_boost_total_multiplier(String multiplier) =>
      _es.candy_boost_total_multiplier(multiplier);

  @override
  String purchase_current_balance(Object amount) =>
      _fil.purchase_current_balance(amount);

  @override
  String purchase_expected_balance(Object amount) =>
      _fil.purchase_expected_balance(amount);

  @override
  String candy_reward_receipt_total(String amount) =>
      _fil.candy_reward_receipt_total(amount);

  @override
  String candy_reward_receipt_balance(String amount) =>
      _fil.candy_reward_receipt_balance(amount);

  @override
  String candy_reward_receipt_purchase_balance(Object amount) =>
      _fil.candy_reward_receipt_purchase_balance(amount);

  @override
  String candy_reward_receipt_expiry(String date) =>
      _fil.candy_reward_receipt_expiry(date);

  @override
  String candy_reward_receipt_semantics(
    String currency,
    String granted,
    String balance,
  ) => _fil.candy_reward_receipt_semantics(currency, granted, balance);

  @override
  String candy_reward_receipt_semantics_balance_unavailable(
    String currency,
    String granted,
  ) => _fil.candy_reward_receipt_semantics_balance_unavailable(
    currency,
    granted,
  );

  @override
  String expiring_today_cotton_only(String cotton) =>
      _id.expiring_today_cotton_only(cotton);

  @override
  String expiring_today_cotton_and_bonus(String cotton, String bonus) =>
      _id.expiring_today_cotton_and_bonus(cotton, bonus);
}

/// Serves [LongestAppLocalizations] for whatever locale the app asks for.
class LongestAppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const LongestAppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => true;

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      LongestAppLocalizations();

  @override
  bool shouldReload(LongestAppLocalizationsDelegate old) => false;
}
