name: picnic_app
description: "Picnic App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+40

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1
  logger: ^2.0.1
  flutter_supabase_chat_core: ^0.10.0
  flutter_secure_storage: ^9.0.0
  faker: ^2.1.0
  file_picker: ^8.0.3
  flutter_login: ^5.0.0
  open_filex: ^4.4.0
  flutter_chat_ui: ^1.6.13
  supabase_extensions: ^1.0.1
  shared_preferences: ^2.2.2
  riverpod: ^2.5.1
  package_info_plus: ^8.0.0
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_svg: ^2.0.9
  riverpod_annotation: ^2.3.5
  file_saver: ^0.2.12
  timeago: ^3.6.1
  intl: ^0.19.0
  image_picker: ^1.0.7
  camera: ^0.10.5+9
  flutter_screenutil: ^5.9.0
  overlay_loading_progress: ^1.0.1
  reflectable: ^4.0.6
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.0
  supabase_auth_ui: ^0.4.4
  card_swiper: ^3.0.1
  infinite_scroll_pagination: ^4.0.0
  flutter_keyboard_visibility: ^6.0.0
  font_awesome_flutter: ^10.7.0
  overlay_support: ^2.1.0
  screen_protector: ^1.4.2
  supabase_flutter: ^2.5.3
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  kakao_flutter_sdk: ^1.9.1+2
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  flutter_chat_types: any
  http: any
  mime: any
  uuid: any
  image: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.5.4
  riverpod_generator: ^2.4.0
  intl_utils: ^2.8.7
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  change_app_package_name: ^1.1.0
flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/vote/
    - assets/icons/header/
    - assets/icons/bottom/
    - assets/icons/line_arrow/
    - assets/mockup/
    - assets/mockup/my/
    - assets/mockup/gallery/
    - assets/mockup/fan/
    - assets/landing/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-ExtraLight.otf
          weight: 100
        - asset: assets/fonts/Pretendard/Pretendard-Thin.otf
          weight: 200
        - asset: assets/fonts/Pretendard/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard/Pretendard-Black.otf
          weight: 900

