name: picnic_app
description: "Picnic App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+72

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  google_mobile_ads: ^5.1.0
  logger: ^2.3.0
  flutter_supabase_chat_core: ^0.10.0
  flutter_secure_storage: ^9.2.2
  faker: ^2.1.0
  file_picker: ^8.0.4
  flutter_login: ^5.0.0
  animated_digit: ^3.2.3
  open_filex: ^4.4.0
  flutter_chat_ui: ^1.6.14
  supabase_extensions: ^1.0.1
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  riverpod: ^2.5.1
  package_info_plus: ^8.0.0
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  load_switch: ^2.1.0
  riverpod_annotation: ^2.3.5
  file_saver: ^0.2.13
  timeago: ^3.6.1
  intl: ^0.19.0
  camera: ^0.11.0+1
  image_cropper: ^7.0.4
  flutter_screenutil: ^5.9.3
  overlay_loading_progress: ^1.0.1
  reflectable: ^4.0.6
  json_annotation: ^4.9.0
  cached_network_image: ^3.3.1
  supabase_auth_ui: ^0.4.4
  card_swiper: ^3.0.1
  infinite_scroll_pagination: ^4.0.0
  flutter_keyboard_visibility: ^6.0.0
  font_awesome_flutter: ^10.7.0
  overlay_support: ^2.1.0
  screen_protector: ^1.4.2
  supabase_flutter: ^2.5.5
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  kakao_flutter_sdk: ^1.9.1+2
  firebase_core: ^3.1.0
  flutter_chat_types: any
  image: ^4.2.0
  image_gallery_saver: ^2.0.3
  photo_manager: ^3.1.1
  permission_handler: ^11.3.1
  audioplayers: ^6.0.0
  vector_math: ^2.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.5.4
  riverpod_generator: ^2.4.0
  intl_utils: ^2.8.7
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  change_app_package_name: ^1.2.0
flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/vote/
    - assets/icons/header/
    - assets/icons/bottom/
    - assets/mockup/
    - assets/mockup/my/
    - assets/mockup/gallery/
    - assets/mockup/pic/
    - assets/landing/
    - assets/sounds/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-ExtraLight.otf
          weight: 100
        - asset: assets/fonts/Pretendard/Pretendard-Thin.otf
          weight: 200
        - asset: assets/fonts/Pretendard/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard/Pretendard-Black.otf
          weight: 900

