name: picnic_app
description: "Picnic App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+10111

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv:
  shimmer:
  advanced_shadows: 0.0.1
  flutter_inner_shadow: ^0.0.1
  universal_platform:
  cupertino_icons:
  flutter_cache_manager:
  another_flutter_splash_screen:
  flutter_native_splash:
  flutter_launcher_icons:
  google_mobile_ads:
  appinio_social_share:
  logger:
  flutter_supabase_chat_core:
  flutter_secure_storage:
  flutter_card_swiper:
  faker:
  file_picker:
  animated_digit:
  open_filex:
  supabase_extensions:
  shared_preferences:
  image_picker:
  riverpod:
  package_info_plus:
  flutter_riverpod:
  hooks_riverpod:
  flutter_svg:
  load_switch:
  riverpod_annotation:
  timeago:
  intl:
  camera:
  image_cropper:
  flutter_screenutil:
  overlay_loading_progress:
  reflectable:
  json_annotation:
  cached_network_image:
  card_swiper:
  infinite_scroll_pagination:
  flutter_keyboard_visibility:
  font_awesome_flutter:
  overlay_support:
  screen_protector:
  supabase_flutter:
  google_sign_in:
  sign_in_with_apple:
  kakao_flutter_sdk_user:
  firebase_core:
  flutter_chat_types:
  image:
  image_gallery_saver:
  in_app_purchase:
  photo_manager:
  permission_handler:
  audioplayers:
  flutter_markdown:
  jwt_decoder:
  vector_math:
  flutter_share:
  path_provider:
  app_tracking_transparency:
  freezed_annotation:
  app_links:
  http:
  deepl_dart:
  watcher:
  archive:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  json_serializable:
  riverpod_generator:
  intl_utils:
  build_runner:
  custom_lint:
  riverpod_lint:
  change_app_package_name:
  freezed:
  intl_translation:

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/images/login/
    - assets/icons/
    - assets/icons/login/
    - assets/icons/vote/
    - assets/icons/header/
    - assets/icons/bottom/
    - assets/icons/store/
    - assets/mockup/
    - assets/mockup/my/
    - assets/mockup/gallery/
    - assets/mockup/pic/
    - assets/landing/
    - assets/sounds/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-ExtraLight.otf
          weight: 100
        - asset: assets/fonts/Pretendard/Pretendard-Thin.otf
          weight: 200
        - asset: assets/fonts/Pretendard/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard/Pretendard-Black.otf
          weight: 900

