// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_eKEsybg4L6lcp198iEzXrNJXhW041zA',
    appId: '1:283818621579:web:44123cac7d0185c48cf28e',
    messagingSenderId: '283818621579',
    projectId: 'ttja-prod',
    authDomain: 'ttja-prod.firebaseapp.com',
    storageBucket: 'ttja-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw5nm42z-OK_v3fZATNEtRuPFFPdzEotQ',
    appId: '1:283818621579:android:b7469e32aad8e9fe8cf28e',
    messagingSenderId: '283818621579',
    projectId: 'ttja-prod',
    storageBucket: 'ttja-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCan6QVK1TaKxQrrzcVK3fI2tqKq1Di7Y',
    appId: '1:283818621579:ios:532a98f177b8aa568cf28e',
    messagingSenderId: '283818621579',
    projectId: 'ttja-prod',
    storageBucket: 'ttja-prod.firebasestorage.app',
    iosBundleId: 'com.example.ttjaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCan6QVK1TaKxQrrzcVK3fI2tqKq1Di7Y',
    appId: '1:283818621579:ios:532a98f177b8aa568cf28e',
    messagingSenderId: '283818621579',
    projectId: 'ttja-prod',
    storageBucket: 'ttja-prod.firebasestorage.app',
    iosBundleId: 'com.example.ttjaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_eKEsybg4L6lcp198iEzXrNJXhW041zA',
    appId: '1:283818621579:web:8e379a0bf3e77a088cf28e',
    messagingSenderId: '283818621579',
    projectId: 'ttja-prod',
    authDomain: 'ttja-prod.firebaseapp.com',
    storageBucket: 'ttja-prod.firebasestorage.app',
  );
}
