// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjTSyaSe5X_HQUoIqiwONHa8dcLBeJOEU',
    appId: '1:922874925395:web:35db2905173531ad9591a6',
    messagingSenderId: '922874925395',
    projectId: 'ttja-447309',
    authDomain: 'ttja-447309.firebaseapp.com',
    storageBucket: 'ttja-447309.firebasestorage.app',
    measurementId: 'G-J4Q7L9TSR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5-FgixW_t8RDw9koOSMKDyuL_xASJGDI',
    appId: '1:922874925395:android:b4d581b0906a87f09591a6',
    messagingSenderId: '922874925395',
    projectId: 'ttja-447309',
    storageBucket: 'ttja-447309.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEvuAygIR4KpVbBcv4aST-Vu9URtLswmc',
    appId: '1:922874925395:ios:e776f25add54d0a59591a6',
    messagingSenderId: '922874925395',
    projectId: 'ttja-447309',
    storageBucket: 'ttja-447309.firebasestorage.app',
    iosClientId: '922874925395-t3anf1iksojil5fc7lss9h4ahr1kgbkm.apps.googleusercontent.com',
    iosBundleId: 'com.fasoo.TTJA',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEvuAygIR4KpVbBcv4aST-Vu9URtLswmc',
    appId: '1:922874925395:ios:4fdc6bf68142200c9591a6',
    messagingSenderId: '922874925395',
    projectId: 'ttja-447309',
    storageBucket: 'ttja-447309.firebasestorage.app',
    iosClientId: '922874925395-j8si8jhhs02sc1475mn7t60cff06l23s.apps.googleusercontent.com',
    iosBundleId: 'com.example.ttjaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjTSyaSe5X_HQUoIqiwONHa8dcLBeJOEU',
    appId: '1:922874925395:web:91203557ff33f1179591a6',
    messagingSenderId: '922874925395',
    projectId: 'ttja-447309',
    authDomain: 'ttja-447309.firebaseapp.com',
    storageBucket: 'ttja-447309.firebasestorage.app',
    measurementId: 'G-48BZF4JTY6',
  );

}