// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBooFK0UjiZ0E1wPRBVZaSrjp-RWtBcS-Y',
    appId: '1:108842433672:web:208e5662b79616b7e4f33d',
    messagingSenderId: '108842433672',
    projectId: 'ttja-bcd75',
    authDomain: 'ttja-bcd75.firebaseapp.com',
    storageBucket: 'ttja-bcd75.firebasestorage.app',
    measurementId: 'G-EEK4E6CSFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp0IZlaILj7_xju_ug428H7k8izT2p3oQ',
    appId: '1:108842433672:android:285c4d4fd59ac3e5e4f33d',
    messagingSenderId: '108842433672',
    projectId: 'ttja-bcd75',
    storageBucket: 'ttja-bcd75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZMZORqornOZs0vp72EbMQfT_mnO512iI',
    appId: '1:108842433672:ios:bf7409e73f1ac54ae4f33d',
    messagingSenderId: '108842433672',
    projectId: 'ttja-bcd75',
    storageBucket: 'ttja-bcd75.firebasestorage.app',
    iosBundleId: 'com.fasoo.TTJA',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZMZORqornOZs0vp72EbMQfT_mnO512iI',
    appId: '1:108842433672:ios:c6ef46f97fb67df7e4f33d',
    messagingSenderId: '108842433672',
    projectId: 'ttja-bcd75',
    storageBucket: 'ttja-bcd75.firebasestorage.app',
    iosBundleId: 'com.example.ttjaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBooFK0UjiZ0E1wPRBVZaSrjp-RWtBcS-Y',
    appId: '1:108842433672:web:a5c086bca44a6c4ee4f33d',
    messagingSenderId: '108842433672',
    projectId: 'ttja-bcd75',
    authDomain: 'ttja-bcd75.firebaseapp.com',
    storageBucket: 'ttja-bcd75.firebasestorage.app',
    measurementId: 'G-55RFPW5ZMZ',
  );

}