
-- Q&A 스레드 정보를 저장할 테이블 생성
CREATE TABLE public.qna_threads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    status TEXT DEFAULT 'open' -- 'open', 'closed'
);

COMMENT ON TABLE public.qna_threads IS 'Q&A 스레드 정보를 저장합니다.';
COMMENT ON COLUMN public.qna_threads.status IS '스레드 상태 (open, closed)';

-- Q&A 메시지를 저장할 테이블 생성
CREATE TABLE public.qna_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id BIGINT REFERENCES public.qna_threads(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    content TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    is_admin_message BOOLEAN DEFAULT FALSE
);

COMMENT ON TABLE public.qna_messages IS 'Q&A 스레드에 속한 메시지를 저장합니다.';
COMMENT ON COLUMN public.qna_messages.is_admin_message IS '관리자가 작성한 메시지인지 여부';

-- Q&A 첨부파일 정보를 저장할 테이블 생성
CREATE TABLE public.qna_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT REFERENCES public.qna_messages(id) ON DELETE CASCADE,
    file_name TEXT NOT NULL,
    file_path TEXT NOT NULL,
    file_type TEXT,
    file_size BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.qna_attachments IS 'Q&A 메시지에 첨부된 파일 정보를 저장합니다.';

-- 실시간 업데이트를 위한 테이블 복제 설정
ALTER TABLE public.qna_threads REPLICA IDENTITY FULL;
ALTER TABLE public.qna_messages REPLICA IDENTITY FULL;
ALTER TABLE public.qna_attachments REPLICA IDENTITY FULL;

-- RLS(Row Level Security) 활성화
ALTER TABLE public.qna_threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.qna_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.qna_attachments ENABLE ROW LEVEL SECURITY;

-- 사용자 역할을 확인하는 헬퍼 함수
CREATE OR REPLACE FUNCTION is_admin()
RETURNS BOOLEAN AS $$
  SELECT (auth.jwt()->>'user_role')::jsonb ? 'admin'
$$ LANGUAGE sql STABLE;

-- RLS 정책 생성

-- qna_threads 테이블 RLS 정책
CREATE POLICY "사용자는 자신의 Q&A 스레드를 보고 생성할 수 있습니다."
ON public.qna_threads FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "관리자는 모든 Q&A 스레드를 볼 수 있습니다."
ON public.qna_threads FOR SELECT
USING (is_admin());

-- qna_messages 테이블 RLS 정책
CREATE POLICY "사용자는 자신의 스레드에 속한 메시지를 보고 작성할 수 있습니다."
ON public.qna_messages FOR ALL
USING (
    (
        auth.uid() = user_id AND
        thread_id IN (SELECT id FROM public.qna_threads WHERE user_id = auth.uid())
    ) OR (
        is_admin() AND is_admin_message = true
    )
);

CREATE POLICY "관리자는 모든 메시지를 볼 수 있습니다."
ON public.qna_messages FOR SELECT
USING (is_admin());


-- qna_attachments 테이블 RLS 정책
CREATE POLICY "사용자는 자신의 메시지에 속한 첨부파일을 관리할 수 있습니다."
ON public.qna_attachments FOR ALL
USING (
    message_id IN (
        SELECT id FROM public.qna_messages WHERE user_id = auth.uid()
    )
);

CREATE POLICY "관리자는 모든 첨부파일을 볼 수 있습니다."
ON public.qna_attachments FOR SELECT
USING (is_admin()); 