-- QnA 카테고리 테이블 및 스레드-카테고리 연결

BEGIN;

-- 1) 카테고리 테이블 생성
CREATE TABLE IF NOT EXISTS public.qna_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    template TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.qna_categories IS 'QnA 질문 카테고리와 기본 템플릿을 보관';

-- 2) threads에 category_id 추가
ALTER TABLE public.qna_threads
    ADD COLUMN IF NOT EXISTS category_id BIGINT NULL REFERENCES public.qna_categories(id) ON DELETE SET NULL;

-- 3) 인덱스
CREATE INDEX IF NOT EXISTS idx_qna_threads_category_id ON public.qna_threads(category_id);

-- 4) 기본 카테고리 시드 (중복 방지 업서트)
INSERT INTO public.qna_categories (name, template)
VALUES
    ('일반 문의', '문의 유형:\n상세 내용:\n기기/OS 정보:\n스크린샷/영상 (선택):'),
    ('버그 제보', '문제 요약:\n재현 절차:\n기대 동작:\n실제 동작:\n앱 버전/OS/기기:\n로그/스크린샷:'),
    ('기능 요청', '요청 기능 요약:\n해결하려는 문제:\n사용 시나리오:\n우선순위/긴급도:\n참고 사례(앱/링크):')
ON CONFLICT (name) DO UPDATE SET
    template = EXCLUDED.template,
    updated_at = NOW();

COMMIT;


