name: Build & Deploy Flutter Web to Vercel Production

on:
  push:
    branches: [ "production" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Flutter web build
        working-directory: packages/client/picnic_app
        run: flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=false

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        working-directory: packages/client/picnic_app/build/web
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel --prod --confirm --token $VERCEL_TOKEN