name: Build & Deploy TTJA App

on:
  push:
    paths:
      - "packages/client/ttja_app/**"
    branches: [ "production" ]
  workflow_dispatch:

jobs:
  build-and-deploy-ttja:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build flutter web
        working-directory: packages/client/ttja_app
        run: flutter build web --release

      - name: Install Vercel CLI
        working-directory: packages/client/ttja_app
        run: npm install -g vercel
  
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel --prod --yes --token $VERCEL_TOKEN
